---
  - name: Reading the file
    shell: cat /home/u55560/test/test.txt
    register: sample

  - debug: msg={{ sample.stdout }}

  - debug: msg="=============================="
  - debug: msg={{ lookup('file','/home/u55560/test/test.txt') }}
