---
  - name: Reading the file
    shell: cat /tmp/test.txt
    register: sample

  - debug: msg={{ sample.stdout }}

  - debug: msg="=============================="
  - debug: msg={{ lookup('file','/tmp/test.txt') }}
